feat(gha): add builder

diff --git a/.github/workflows/process_pr.yml b/.github/workflows/process_pr.yml
--- a/.github/workflows/process_pr.yml
+++ b/.github/workflows/process_pr.yml
@@ -8,6 +8,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+      
       - name: Run Linter
         run: |
           set +e
@@ -19,22 +20,66 @@ jobs:
             echo -e "${log}"
             echo EOF
           } >> "$GITHUB_ENV"
-      - name: Add Comment
-        run: echo -e "${LINTER_CODE}\n${LINTER_LOG}" | gh issue comment "$NUMBER" -F -
+      
+      - if: env.LINTER_CODE != '0'
+        name: Comment Linter Report
+        run: echo -e "${LINTER_LOG}" | gh issue comment "$NUMBER" -F -
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GH_REPO: ${{ github.repository }}
           NUMBER: ${{ github.event.number }}
-      - name: Change PR to Draft
-        if: env.LINTER_CODE != '0'
+      
+      - if: env.LINTER_CODE != '0'
+        name: Change PR to Draft
         env:
           GH_TOKEN: ${{ github.token }}
         run: gh pr ready ${{ github.event.pull_request.number }} --undo
+      
+      - if: env.LINTER_CODE != '0'
+        name: Fail PR
+        uses: actions/github-script@v7
+        with:
+          script: core.setFailed('Linter returned an error. Please fix the errors and try again.')
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+        
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-      # - name: Fail PR
-      #   uses: actions/github-script@v7
-      #   with:
-      #     script: core.setFailed('This PR is not ready for review.')
+      - name: Build Docker Image
+        run: |
+          set +e
+          bash scripts/linter.sh
+          code="$?"
+          echo "BUILDER_CODE=$code" >> $GITHUB_ENV
+          echo "BUILDER_LOG=Builder: ✅ Build successful. >> $GITHUB_ENV "
+      - name: Add Build Info to Comment
+        if: env.BUILDER_CODE != '0'
+        run: |
+          {
+            echo 'BUILDER_LOG<<EOF'
+            echo -e "Builder: ❌ Build failed. Please check the Dockerfile for errors."
+            echo -e "Builder: 👉 Check the logs for more information: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
+            echo EOF
+          } >> "$GITHUB_ENV"
+        
+      - name: Comment Build Report
+        run: echo -e "${LINTER_LOG}\n${BUILDER_LOG}" | gh issue comment "$NUMBER" -F -
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GH_REPO: ${{ github.repository }}
+          NUMBER: ${{ github.event.number }}
+      - if: env.BUILDER_CODE != '0'
+        name: Change PR to Draft
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: gh pr ready ${{ github.event.pull_request.number }} --undo
+        
+      - if: env.BUILDER_CODE != '0'
+        name: Fail PR
+        uses: actions/github-script@v7
+        with:
+          script: core.setFailed('Linter returned an error. Please fix the errors and try again.')
 
   # merge-pr:
   #   name: Merge PR Request
